version: "3"

services:
  db:
    image: mysql:5.7
    container_name: hew
    restart: always
    volumes:
      - ../mysql/data:/var/lib/mysql
      - ../mysql/conf:/etc/mysql/conf.d
      - ../mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hew2020
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      # TZ: 'Asia/Tokyo'
    ports:
      - "13306:3306"