// 通知
export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION'

// ログインダイアログ
export const OPEN_LOGIN_DIALOG = 'OPEN_LOGIN_DIALOG'
export const CLOSE_LOGIN_DIALOG = 'CLOSE_LOGIN_DIALOG'

// ログイン処理
export const JWT_LOGIN = 'JWT_LOGIN'
export const JWT_LOGOUT = 'JWT_LOGOUT'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const UNAUTHENTICATE_USER = 'UNAUTHENTICATE_USER'

// リクエスト
export const START_REQUEST = 'START_REQUEST'
export const COMPLETE_REQUEST = 'COMPLETE_REQUEST'
