[API]
port     = ":3306"
version  = "alpha"

[DB]
dbms = "mysql"
user = "root"
pass = "secret"
protocol = "tcp(db)"
dbname = "hew2020"

[TOKEN]
exp = "24"

[GooglePlace]
key = "AIzaSyD5Z2K-JgM-o-rH2KzW4WwS85HOm2nuil0" # ここにkeyを入力
types = "convenience_store"